import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";

import Menubar from "@components/MenuBar";

import "primereact/resources/themes/saga-blue/theme.css";
import "primeicons/primeicons.css";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Le compte juste",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div
          style={{
            display: "flex",
            justifyContent: "flex-start",
            flexDirection: "row",
            alignItems: "center",
            gap: "1em",
          }}
        >
          <Image alt="" src={"/icon.png"} width={50} height={50} />
          <h1>Le compte juste</h1>
        </div>
        <Menubar />
        {children}
      </body>
    </html>
  );
}
